namespace Fr1end1y.Cms.Configuration;

// Custom configuration settings for the project using the ASP.NET Core options pattern
// https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-9.0
public class Fr1end1yOptions
{
	// The key of the custom section in `appsettings.json` (or whatever
	// configuration source is used).
	public const string SectionKey = "Fr1end1y";

	// When set to `true`, ASP.NET will be configured to serve static files
	// from the Eleventy output directory.
	public bool ServeEleventySite { get; set; } = false;

	// The directory containing the static site generated by Eleventy.
	// https://www.11ty.dev/docs/config/#output-directory
	// Should be relative to `IHostEnvironment.ContentRootPath`.
	// https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostenvironment.contentrootpath?view=net-9.0-pp
	public string EleventyOutputDir { get; set; } = "../Fr1end1y.Site/_site/";

	// When set to `true`, an Eleventy build will be triggered when content is
	// published.
	public bool BuildEleventySite { get; set; } = false;

	// The root directory of the Eleventy project.
	// Should be relative to `IHostEnvironment.ContentRootPath`.
	// https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostenvironment.contentrootpath?view=net-9.0-pp
	public string EleventyRootDir { get; set; } = "../Fr1end1y.Site/";
}
