// This file is auto-generated by @hey-api/openapi-ts
import { createClient, createConfig } from '@hey-api/client-fetch';
export const client = createClient(createConfig());
/**
 * @deprecated
 */
export const getContent = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v1/content',
        ...options
    });
};
export const getContent20 = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v2/content',
        ...options
    });
};
/**
 * @deprecated
 */
export const getContentItem = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v1/content/item',
        ...options
    });
};
/**
 * @deprecated
 */
export const getContentItemByPath = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v1/content/item/{path}',
        ...options
    });
};
export const getContentItemByPath20 = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v2/content/item/{path}',
        ...options
    });
};
/**
 * @deprecated
 */
export const getContentItemById = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v1/content/item/{id}',
        ...options
    });
};
export const getContentItemById20 = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v2/content/item/{id}',
        ...options
    });
};
export const getContentItems20 = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v2/content/items',
        ...options
    });
};
/**
 * @deprecated
 */
export const getMedia = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v1/media',
        ...options
    });
};
export const getMedia20 = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v2/media',
        ...options
    });
};
/**
 * @deprecated
 */
export const getMediaItem = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v1/media/item',
        ...options
    });
};
/**
 * @deprecated
 */
export const getMediaItemByPath = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v1/media/item/{path}',
        ...options
    });
};
export const getMediaItemByPath20 = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v2/media/item/{path}',
        ...options
    });
};
/**
 * @deprecated
 */
export const getMediaItemById = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v1/media/item/{id}',
        ...options
    });
};
export const getMediaItemById20 = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v2/media/item/{id}',
        ...options
    });
};
export const getMediaItems20 = (options) => {
    return (options?.client ?? client).get({
        url: '/umbraco/delivery/api/v2/media/items',
        ...options
    });
};
